### PR TITLE
[Al-35 Backend] Update skills

### PR DESCRIPTION
**Pull request by shyatup**
[Link to Jira](https://is212g1t5.atlassian.net/browse/AL-35)
[Link to GSheets](https://docs.google.com/spreadsheets/d/1aIM9Zc_wtMzg6MWyOuN-DdLgag2eKoCOT44M1iTcLTw/edit#gid=853076560)
- [ ] [Happy Path] HR staff can update skill name, category, description, staff
- [ ] [Negative Path] Validation - If there are completely no changes
- [ ] [Negative Path] Validation - If there are empty fields (all fields are required in this case)
- [ ] [Boundary Testing] Validation - Ensure that the updated skill name does not already exist in the database
- [ ] [Boundary Testing] Validation - Cannot navigate to a skill that does not exist (i.e. if database has 2 rows of data, you cannot call row 3 because it does not exist)

### CODE REVIEW

**Comment by shyatup** [comment]
Go through the acceptance criteria listed, if there are any additional tests that I have missed out feel free to leave comments so that I can edit the code!

**Review by jacky-teo — COMMENTED** [review]
Added one more condition to check if skill name is the same but the skill desc is updated.

**Comment by Vasn** [comment]
This one is just merge into backend not frontend right?

**Comment by shyatup** [comment]
> This one is just merge into backend not frontend right?
oh right, will update the PR tomorrow!!

**Comment by shyatup** [comment]
Updated destination of merge, added changes in the backend to the branch to avoid merge conflict; Please review/test @Vasn @jacky-teo

**Comment by Vasn** [comment]
Updated the Flask-Cors in requirements file for container and removed GET method since is update

**Pull request merged**
