### PR TITLE
Show skill despite inactive & show course status

### PR DESCRIPTION
**Pull request by jacky-teo**
Changed the frontend to as per how we discussed, user can now see completion status as Registration Rejected / Not enrolled.
 
 Skill name can now be seen if its empty

### CODE REVIEW

**Comment by jacky-teo** [comment]
image
This is how learning journey details will now look like

**Comment by jacky-teo** [comment]
Fixed Learning Journey Again
image

**Comment by shyatup** [comment]
think you should remove the actions column and put the update button somewhere else because the click to update is not specific to the skill-course mapping but to the entire learning journey itself 😄 

image
image

**Comment by jacky-teo** [comment]
This is the final version
image

**Pull request merged**
